name: test

on:
  push:
    branches:
      - master
      - NV_GP-21
    pull_request:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-versions: "3.10"
    - uses: abatilo/actions-poetry@v2.1.3
      with:
        poetry-versions: 1.8.3
    - run: wget -P cv_algorithm/model/ https://volleyball-player-detection.vinnich.uk/{yolov3.cfg,yolov3_ckpt_600.pth}
    - run: poetry install
    - run: poetry run pytest test/
